sudo: required
services:
  - docker

before_install:
  - docker build -t abhishekmadiraju/docker-react-practice .

script:
  - docker run -e CI=true abhishekmadiraju/docker-react-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-practice"
  env: "DockerReactPractice-env"
  bucket_name: "elasticbeanstalk-us-east-1-407150809907"
  bucket_path: "docker-react-practice"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
